In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [3]:
type(arr)

numpy.ndarray

In [4]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
arr_2d.ndim

2

In [6]:
arr_2d.size

8

In [7]:
arr_2d.shape #use to show the row and column (row, column)

(2, 4)

In [8]:
arr_2d.dtype

dtype('int32')

In [9]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])