In [2]:
import numpy as np

In [6]:
mtx_1=np.array([[1,1,1], [1,1,1], [1,1,1]])
print(mtx_1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [16]:
mat=np.ones(5)
print(mat)
mat.dtype

[1. 1. 1. 1. 1.]


dtype('float64')

In [19]:
#creting 3x4 matrix
new_mat=np.ones((3,4))
print(new_mat)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [24]:
a=np.ones((3,4), dtype = int)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [29]:
zero_mat=np.zeros((4,6))
print(zero_mat)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [32]:
zero_mat=np.zeros((4,6), dtype = bool)
print(zero_mat)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [35]:
zero_mat=np.zeros((4,6), dtype = str)
print(zero_mat)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [37]:
zero_mat=np.ones((4,6), dtype = bool)
print(zero_mat)

[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]


In [38]:
zero_mat=np.ones((4,6), dtype = str)
print(zero_mat)

[['1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1']]


In [41]:
emp_mat=np.empty((3,3))
print(emp_mat)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 7.76671195e-321]
 [1.05699242e-307 3.11523242e-307 2.14321575e-312]]
