# NumPy Functions: 

In [4]:
import numpy as np

# arange()

In [5]:
# syntax :  no.arange(start, ende, setps)

In [8]:
arr_1d = np.arange(1, 13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [10]:
#print only even value
arr_even = np.arange(1, 13, 2)
print(arr_even)

[ 1  3  5  7  9 11]


# linespace()

In [13]:
np.linspace(1, 5, 4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

# reshape()

In [17]:
arr_2d= arr_1d.reshape(2, 6)
print(arr_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [20]:
arr_3d = arr_1d.reshape(2,3,2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# ravel()

In [22]:
one_darr=arr_3d.ravel()
print(one_darr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# flatten()

In [29]:
arr_3d.flatten('C')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose()

In [30]:
arr_2d.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])