# Mathemetical Opertation Using NumPy

In [2]:
import numpy as np

In [7]:
#arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

#arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [12]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
arr1+arr1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [15]:
#Addition function
np.add(arr1, arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [17]:
#Subtract function
np.subtract(arr1, arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
#divide
np.divide(arr1, arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
#multiplication
np.multiply(arr1, arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [25]:
#matrix product using dot 
arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [39]:
#find max value
arr1.max()
#find min value
arr1.min()

1

In [37]:
#find max value index
arr1.argmax()

#find min value index
arr1.argmin()

0

In [31]:
#find the max value in colom
arr1.max(axis = 0)# here 0 is repersent the colom

array([7, 8, 9])

In [33]:
#find the max value in row
arr1.max(axis = 1)# here 1 is repersent the row

array([3, 6, 9])

In [35]:
#find the min value in colom
arr1.min(axis = 0)# here 0 is repersent the colom


array([1, 2, 3])

In [40]:
#find the min value in row
arr1.min(axis = 1)# here 1 is repersent the row

array([1, 4, 7])

In [43]:
#sum() function
np.sum(arr1)

45

In [45]:
#find the sum of all colom
np.sum(arr1, axis = 0)

array([12, 15, 18])

In [47]:
#find the sum of all row
np.sum(arr1, axis = 1)

array([ 6, 15, 24])

In [49]:
#finding the mean of the matrix
np.mean(arr1)

5.0

In [51]:
#finding the square root of each element present in the matrix.
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [53]:
#finding standerd division
np.std(arr1)

2.581988897471611

In [55]:
#exponent
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [56]:
#find log
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])